# Generated by Django 5.2.7 on 2025-12-22 12:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_author_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
